### ISSUE TITLE
How to recorded data of group_user_table?

### ISSUE THREAD

**Issue by awesomenkj** [viraj-khatavkar/group-chat-app-laravel-pusher#2]
I cloned this repository to my local, and working properly. 

But I'm not sure how the data of group_user_table is recorded?

I can see there is no any special codes for that.

Hope to hear soon

**Comment by mercuryskies** [comment]
Hi. Same problem :(

**Comment by awesomenkj** [comment]
Hi @mercuryskies 
I solved  this issue.

You must check this https://laravel.com/docs/5.6/eloquent-relationships
